This page contains the following errors:
error on line 86 at column 96: EntityRef: expecting ';'
Below is a rendering of the page up to the first error.
:root { --background: 15 85% 76%; --foreground: 4 100% 9%; --muted: 15 79% 63%; --muted-foreground: 4 100% 9%; --popover: 15 100% 98%; --popover-foreground: 4 100% 9%; --card: 15 100% 98%; --card-foreground: 4 100% 9%; --border: 15 79% 63%; --input: 15 79% 63%; --primary: 16 100% 60%; --primary-foreground: 14 100% 99%; --secondary: 15 100% 83%; --secondary-foreground: 4 100% 9%; --accent: 15 100% 83%; --accent-foreground: 4 100% 9%; --destructive: 0 84.2% 60.2%; --destructive-foreground: 60 9.1% 97.8%; --ring: 16 100% 60%; --radius: 0.6rem; } .dark { --background: 356 100% 0%; --foreground: 15 100% 95%; --muted: 18 100% 23%; --muted-foreground: 15 100% 95%; --popover: 7 100% 9%; --popover-foreground: 15 100% 95%; --card: 7 100% 9%; --card-foreground: 15 100% 95%; --border: 18 100% 23%; --input: 18 100% 23%; --primary: 20 100% 41%; --primary-foreground: 14 100% 99%; --secondary: 18 100% 23%; --secondary-foreground: 15 100% 95%; --accent: 18 100% 23%; --accent-foreground: 15 100% 95%; --destructive: 0 62.8% 30.6%; --destructive-foreground: 0 0% 98%; --ring: 20 100% 41%; --radius: 0.6rem; } import { createHotContext } from "/@vite/client"; const hot = createHotContext("/__dummy__runtime-error-plugin"); function sendError(error) { if (!(error instanceof Error)) { error = new Error("(unknown runtime error)"); } const serialized = { message: error.message, stack: error.stack, }; hot.send("runtime-error-plugin:error", serialized); } window.addEventListener("error", (evt) => { sendError(evt.error); }); window.addEventListener("unhandledrejection", (evt) => { sendError(evt.reason); }); import RefreshRuntime from "/@react-refresh" RefreshRuntime.injectIntoGlobalHook(window) window.$RefreshReg$ = () => {} window.$RefreshSig$ = () => (type) => type window.__vite_plugin_react_preamble_installed__ = true SAGE - Strategic Adaptive Generative Engine